spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo-studio-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  JWT_SECRET: abcd
  EXPIRATION_TIME: 43200000 #1hr
logging:
  level:
    org:
      springframework:
        security: DEBUG